language: python

python:
- '3.6'
- '3.7'
- '3.8'

install:
- pip install --upgrade .
- pip install --upgrade --requirement test-requirements.txt

script:
- flake8 bundlebuilder/
- pytest --verbose tests/unit/
